### PR TITLE
Print track names when invalid track provided

### LINKED ISSUE #125: Print allTracks to console/logs
It would be helpful to get allTracks names printed to logs for finding issues/ typo e.t.c. 

https://github.com/r0adkll/upload-google-play/blob/623184c55db44a7ff8f00e58154b558fdcf7af23/src/edits.ts#L141

### PR DESCRIPTION
**Pull request by rfogar2**
To make it easier diagnosing invalid tracks, print the track names.

Resolves #125

### CODE REVIEW

**Comment by miduch** [comment]
any plans to merge this?

**Comment by boswelja** [comment]
Sorry for the delay, seems like GitHub has not been notifying me of updates here

**Comment by boswelja** [comment]
Please make sure you have rebuilt the project via `npm run build`. Once that is done I'm happy to merge this :)

**Comment by miduch** [comment]
really looking forward for this one, can you please merge ? thanks!

**Comment by boswelja** [comment]
I've taken over this, see #151

**Pull request closed without merging**
