### PR TITLE
Add support for glob

### PR DESCRIPTION
**Pull request by DiogoAbu**
The releaseFiles option now supports glob using [fast-glob](https://www.npmjs.com/package/fast-glob).

Example:
```yaml
releaseFiles: ./app/build/outputs/bundle/release/*.aab
```

### CODE REVIEW

**Review by r0adkll — APPROVED** [review]
:shipit:

**Comment by koperko** [comment]
I think that merging this broke this action in our recent runs .. Here's the stack trace
```
nternal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'fast-glob'
Require stack:
- /home/runner/work/_actions/r0adkll/upload-google-play/master/lib/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/r0adkll/upload-google-play/master/lib/main.js:36:37)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) ***
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/r0adkll/upload-google-play/master/lib/main.js'
  ]
```

**Comment by r0adkll** [comment]
ah, I guess the bundled node modules didn't get updated. Let me push a hotfix for this. In the meantime you can target the previous version, `v1.0.12`

**Comment by r0adkll** [comment]
okay, @koperko I have fixed the missing node modules and updated the pointers of both `v1.0.13` and `v1` to point to the fixed version

**Pull request merged**
