### PR TITLE
Fix: default behavior when status is unspecified

### LINKED ISSUE #80: This error popped up recently! any help?
I am getting this error all of sudde
Capture
n

### PR DESCRIPTION
**Pull request by dougkeen**
Fixes #80

### CODE REVIEW

**Review by tobiasschuerg — APPROVED** [review]

**Review by boswelja — APPROVED** [review]

**Comment by boswelja** [comment]
@r0adkll Can we get this merged asap? The action simply doesn't run unless you explicitly specify a status

**Comment by heavybeard** [comment]
Is this repo alive?

**Comment by boswelja** [comment]
The owner is known to disappear for months at a time, we don't know when they come back unfortunately

**Comment by boswelja** [comment]
Welcome back! Even if it is temporary 😄
I'm happy to be made a maintainer or have it transferred to me, up to you whether you want it kept under your account

**Comment by r0adkll** [comment]
Invited! I'd say to keep it here so as to keep existing usages up to date. I'll make sure that you have the permissions to manage anything, but can pop back in if not and need be. Thanks for helping me here on this repository, I greatly appreciate it 😄

**Comment by heavybeard** [comment]
@r0adkll I feel you. I was in the same detox process some years ago. You have my support, in case the words of a complete stranger mattered.

**Pull request merged**
