### PR TITLE
Use double-quotes in descriptions

### PR DESCRIPTION
**Pull request by AChep**

### CODE REVIEW

**Comment by AChep** [comment]
Should fix https://github.com/r0adkll/upload-google-play/issues/36

**Review by michaelbukachi — APPROVED** [review]

**Review by r0adkll — APPROVED** [review]
:shipit:

**Comment by amul047** [comment]
Hey @AChep ,

Do you know why having the quotes makes a difference? You got any links to github action pages/code?

I am encountering the same stack trace for a private composite action.

Thanks

**Comment by AChep** [comment]
@amul047 you can check the line 24:
```
'I'm'
```
Leads to an error, because it's confused where the string ends.

**Comment by amul047** [comment]
Ah, Thanks :) 

Now, I gotta figure out what's wrong on my one.

You got a good tool to pick yaml mistakes like this? Maybe an add-on for Visual studio code?

**Pull request merged**
